### ISSUE TITLE
solution / fitresult appears to depend on gamma_seed for trials with small ns

### ISSUE THREAD

**Issue by HansN87** [IceCubeOpenSource/skyllh#2]

**Comment by chiarabellenghi** [comment]
gamma_seed dependence on the median number of injected signal events from the sensitivity calculation.

[mean_n_sig_for_gseed_atTXS_gamma2.00_5yr_trad_diff_PS.pdf](https://github.com/IceCubeOpenSource/skyllh/files/4386603/mean_n_sig_for_gseed_atTXS_gamma2.00_5yr_trad_diff_PS.pdf)

**Comment by chiarabellenghi** [comment]
gamma_seed dependence on the median number of injected signal events from the sensitivity calculation.

![mean_n_sig_for_gseed_atTXS_gamma2 00_5yr_trad_diff_PS](https://user-images.githubusercontent.com/62283616/77638465-82789580-6f57-11ea-906f-f4cea766e763.png)

**Comment by chiarabellenghi** [comment]
Dependence of median number of signal events from the sensitivity calculation on the gamma_seed.

![mean_n_sig_for_gseed_atTXS_gamma2 00_5yr_trad_diff_PS](https://user-images.githubusercontent.com/62283616/77639923-ca98b780-6f59-11ea-8472-268d435ba1d4.png)

**Comment by HansN87** [comment]
some local experiments with LBFGS:
- finite difference gradients: no improvement
- changes to gradient tolerance: no improvement
- changes to _one_plus_alpha parameters (skyllh llhratio function): no improvement

**Comment by HansN87** [comment]
looks like problem was caused by using ns_seed = 0.1 as default. The is most likely explained by the fact that the gradient along gamma vanishes towards ns = 0.

![Screenshot from 2020-04-10 20-43-25](https://user-images.githubusercontent.com/5701845/79014821-f6c45300-7b6b-11ea-8761-4ec3636e2a00.png)

closing for now.
