### ISSUE TITLE
trials differ depending on sorting of MC events

### ISSUE THREAD

**Issue by HansN87** [IceCubeOpenSource/skyllh#31]
we observed indications that martin's event sorting feature leads to different outcomes.

see:

Create a trial data manager and add the required data fields.
(1) tdm = TrialDataManager(index_field_name='ang_err')
(2) tdm = TrialDataManager(index_field_name=None)

expected behavior:
trials produced using (1) should be identical to (2) but with reduced runtime.

**Comment by martwo** [comment]
This issue has been resolved. The cause was the settings of the minimizer which were too stringent on the function value resulting in different outcomes for small LH function value changes.
