### ISSUE TITLE
support for signal pdfs represented by 4D splinetables (last dimension: gamma parameter) 

### ISSUE THREAD

**Issue by HansN87** [IceCubeOpenSource/skyllh#38]
instead of reading several 3D splinetables along gamma axis, we could read one 4D splinetable and avoid custom interpolation in python.

**Comment by HansN87** [comment]
this can be done. prototype here.
https://github.com/tglauch/ICPointSource/blob/master/scripts/frankenstein_likelihood/likelihood_sbratio.py

we now need a corresponding interface.

**Comment by martwo** [comment]
This feature is implemented now. But speed is reduced due to inefficient gradient calculation. Instead one should use 3D KDEs with external gamma interpolation which caches PDF values for higher efficiency.
