### ISSUE TITLE
create_pseudo_data_file merges background and signal pseudo data in one DataFieldRecordArray. It would be helpful for analysis if they were stored separately.

### ISSUE THREAD

**Issue by HansN87** [IceCubeOpenSource/skyllh#45]
https://github.com/IceCubeOpenSource/skyllh/blob/9c7695e02f04648a5cfb138d459b7f95530edba0/skyllh/core/analysis.py#L458

one could combine signal and background pseudo data during the loading step.
https://github.com/IceCubeOpenSource/skyllh/blob/9c7695e02f04648a5cfb138d459b7f95530edba0/skyllh/core/utils/trials.py#L77

**Comment by martwo** [comment]
This feature is implemented now. Use the method Analysis.do_trial_with_given_bkg_and_sig_pseudo_data when performing trials with pre-stored trial data.
