### ISSUE TITLE
option to evaluate energy pdf at reconstructed declination instead of source declination

### ISSUE THREAD

**Issue by HansN87** [IceCubeOpenSource/skyllh#56]
evaluating at source declination is the formally correct approach, but being able to evaluate at reconstructed declination can stabilize pdfs because of the averaging effect.

this should be an option.

**Comment by martwo** [comment]
Looking into this the cleaniest way is to create separate info files for the KDE. I'm wondering how the KDEs are produced in the sin_src_dec dimension. What is the range and does it cover the entire sin_dec range? Because that's necessary in order to just swap the axis data.

**Comment by HansN87** [comment]
I have done some tests with separate info files. It works fine - but I don't think we still need this option. So I am closing this for now.
