### ISSUE TITLE
skyllh KDE input: bins -> bin_centers

### ISSUE THREAD

**Issue by HansN87** [IceCubeOpenSource/skyllh#6]
KDE input is evaluated on a grid (bin_centers).
Current naming convention gives impression it is handled as bin_edges.

from mwolf
"I think we should keep the naming of the kde properties accurate. For instance, if it is bin centers it should be called bin_centers not just bins In Skyllh it is used as bin edges but magically it seems to work. But it might create big confusion down the line"

**Comment by tomaskontrimas** [comment]
Closed with https://github.com/tglauch/ICPointSource/commit/dd4600728eef650167e8d13a4f8e17e34f1d1493
