### ISSUE TITLE
Undefined function behavior

### ISSUE THREAD

**Issue by martwo** [IceCubeOpenSource/skyllh#64]
The function polynomial_fit has an undefined behavior when deg is not 1 or 2. It that case it returns just the input argument ns.
https://github.com/IceCubeOpenSource/skyllh/blob/14c606fd32c680ad03fe6a5dff01f38453427c7a/skyllh/core/analysis_utils.py#L86

**Comment by chiarabellenghi** [comment]
Solved. Now when deg is not 1 or 2 it raises a ValueError.
