### ISSUE TITLE
SpatialBoxEventSelectionMethod silent fail

### ISSUE THREAD

**Issue by tomaskontrimas** [IceCubeOpenSource/skyllh#79]
SpatialBoxEventSelectionMethod silently fails to get initialized while using NumPy version >=19.0 and falls back to selecting all events.

```
numpy/core/_asarray.py:83: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return array(a, dtype, copy=False, order=order)
```

**Comment by tglauch** [comment]
I think in the end it was not related to the numpy version, but to the specific i3skyllh installation. Shouldn't happen with the latest version anymore. So I'd close it for now.
